
DROP TABLE IF EXISTS public.account CASCADE;
DROP TABLE IF EXISTS public.inventory CASCADE;
DROP TABLE IF EXISTS public.classification CASCADE;
DROP TYPE IF EXISTS public.account_type CASCADE;


CREATE TYPE public.account_type AS ENUM (
  'Client',
  'Employee',
  'Admin'
);


CREATE TABLE public.classification (
  classification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classification_name VARCHAR(30) NOT NULL
);


CREATE TABLE public.inventory (
  inv_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inv_make VARCHAR(50) NOT NULL,
  inv_model VARCHAR(50) NOT NULL,
  inv_year VARCHAR(4) NOT NULL,
  inv_description TEXT NOT NULL,
  inv_image VARCHAR(100) NOT NULL,
  inv_thumbnail VARCHAR(100) NOT NULL,
  inv_price NUMERIC(10,2) NOT NULL,
  inv_miles INTEGER NOT NULL,
  inv_color VARCHAR(20) NOT NULL,
  classification_id INTEGER NOT NULL
);


ALTER TABLE public.inventory
ADD CONSTRAINT fk_classification
FOREIGN KEY (classification_id)
REFERENCES public.classification(classification_id);


CREATE TABLE public.account (
  account_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_firstname VARCHAR NOT NULL,
  account_lastname VARCHAR NOT NULL,
  account_email VARCHAR NOT NULL,
  account_password VARCHAR NOT NULL,
  account_type public.account_type NOT NULL DEFAULT 'Client'
);


INSERT INTO public.classification (classification_name)
VALUES
  ('Sport'),
  ('SUV'),
  ('Truck'),
  ('Sedan');


INSERT INTO public.inventory
(inv_make, inv_model, inv_year, inv_description, inv_image, inv_thumbnail, inv_price, inv_miles, inv_color, classification_id)
VALUES
('GM', 'Hummer', '2006', 'small interiors but capable off-road vehicle.', '/images/hummer.jpg', '/images/hummer-tn.jpg', 35000.00, 58000, 'Black', 2),
('Ferrari', 'F40', '1992', 'A legendary sports car with raw performance.', '/images/ferrari-f40.jpg', '/images/ferrari-f40-tn.jpg', 450000.00, 12000, 'Red', 1),
('Lamborghini', 'Aventador', '2020', 'Exotic styling and massive power for true enthusiasts.', '/images/aventador.jpg', '/images/aventador-tn.jpg', 393695.00, 5000, 'Yellow', 1),
('Ford', 'F-150', '2019', 'Reliable work truck with strong towing capacity.', '/images/f150.jpg', '/images/f150-tn.jpg', 28995.00, 40000, 'Blue', 3),
('Toyota', 'Camry', '2021', 'Comfortable sedan with good fuel economy.', '/images/camry.jpg', '/images/camry-tn.jpg', 24995.00, 15000, 'White', 4);

-- =========================================
-- 8) ASSIGNMENT 2 - QUERY 4
-- =========================================
UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM'
  AND inv_model = 'Hummer';

-- =========================================
-- 9) ASSIGNMENT 2 - QUERY 6
-- =========================================
UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images', '/images/vehicles'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images', '/images/vehicles');